# Generated by Django 5.0.6 on 2024-06-22 11:08

import django.db.models.deletion
import workspaces.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.IntegerField(blank=True, choices=[(1, 'Pro'), (2, 'Scale'), (3, 'Enterprise')], null=True)),
                ('business_name', models.CharField(max_length=80)),
                ('industry', models.CharField(blank=True, choices=[('\u2060Retail', '\u2060Retail'), ('\u2060Hospitality', '\u2060Hospitality'), ('\u2060Media', '\u2060Media'), ('\u2060Technology', '\u2060Technology'), ('\u2060Finance', '\u2060Finance'), ('\u2060Sport', '\u2060Sport'), ('\u2060Beauty', '\u2060Beauty'), ('\u2060Automotive', '\u2060Automotive')], max_length=60, null=True)),
                ('assistant_id', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('root_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_space_root_user', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkSpaceInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_code', models.CharField(default=workspaces.models.create_workspace_invite, max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.workspace')),
            ],
        ),
    ]
